### ISSUE TITLE
Wrong length of AD.CUST_BOR_ORDER_ID

### ISSUE THREAD

**Issue by o15a3d4l11s2** [veneliniliev/borica-3ds#3]
First of all - thank you very much for the time and efforts you have put into the library!

According to Borica the max length of the field is 22 characters (6 character for the ORDER + 16 random characters).
In the implementation the string is cut to the 16th char:
```php
'AD.CUST_BOR_ORDER_ID' => mb_substr($orderString, 0, 16)
```
Could you please update it?

**Comment by o15a3d4l11s2** [comment]
@veneliniliev, this is a very small change, but if you prefer I can create a pull request for it.

**Comment by veneliniliev** [comment]
https://github.com/veneliniliev/borica-3ds/releases/tag/1.3.1
new version tagged with fix, tnx!
