### ISSUE TITLE
PHP 5.6 support

### ISSUE THREAD

**Issue by PlamenVasilev** [veneliniliev/borica-3ds#4]
The required version in composer.json is 5.6, but when I try to install it on legasy PHP 5.6 project I got an error from a dependent package "php-enum" which require PHP 7.3 or 8

```
Problem 1
    - myclabs/php-enum 1.8.3 requires php ^7.3 || ^8.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - myclabs/php-enum 1.8.3 requires php ^7.3 || ^8.0 -> your PHP version (5.6.30) does not satisfy that requirement.
    - Installation request for myclabs/php-enum 1.8.3 -> satisfiable by myclabs/php-enum[1.8.3].
```

**Comment by veneliniliev** [comment]
Направих няколко теста.
с php 5.6 се ползва myclabs/php-enum (1.6.6) която е за 5.4+ и няма никакъв проблем с инсталацията.
